# sudo apt-get install gcc-arm-none-eabi binutils-arm-none-eabi gdb-arm-none-eabi openocd

image:
    name: stm32
    
variables:
    GIT_SUBMODULE_STRATEGY: recursive


stages:
    - pages
    - build
    - test

build:
    stage: build
    script: time CLEANBUILD=true ./build.sh
    cache:
        key: build-cache
        paths:
        - build/Drivers
        - build/Middlewares
    artifacts:
        paths:
            - build/Rflw.bin
        expire_in: 1 week

test:
    stage: test
    script: file build/Rflw.bin

pages:
    stage: pages
    script: 
    - doxygen Rflw
    - mv docs/html/ public/
    artifacts:
        paths:
        - public
    only:
    - master
